[package]
name = "seamdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.72"
bytesize = "1.2.0"
compact_str = "0.7.1"
derivative = "2.2.0"
hashlink = "0.8.3"
rdkafka = "0.33.2"
tokio = {version = "1.30.0", features = ["full"]}
uriparse = "0.6.4"

[dev-dependencies]
serial_test = "2.0.0"
speculoos = "0.11.0"
test-case = "3.1.0"
testcontainers = "0.14.0"
