[package]
name = "seamdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
compact_str = "0.7.1"
hashlink = "0.8.3"
uriparse = "0.6.4"

[dev-dependencies]
speculoos = "0.11.0"
test-case = "3.1.0"
